name: Build NintendoSwitchPkg

on: [push]

jobs:
  job_1:
    name: Build NintendoSwitchPkg
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          export PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-elf/:$PATH"
          
          cd /opt
          wget http://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-elf/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-elf.tar.xz
          tar -xf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-elf.tar.xz
          rm -rf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-elf.tar.xz
          
          mkdir workdir
          cd workdir
        
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common uuid-dev
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          rm -rf packages-microsoft-prod.deb
          
          git clone https://github.com/fail0verflow/shofel2.git
          git clone https://github.com/WolfLink115/Coreboot.git --recursive
          git clone https://github.com/tianocore/edk2.git --recursive
          
          cd edk2
          git clone https://github.com/WolfLink115/NintendoSwitchPkg.git --recursive
          
          cd ../shofel2/exploit && make
          cd ../../edk2
          source edksetup.sh
          make -C BaseTools/
          cp NintendoSwitchPkg/Tools/run-build.sh . && ./run-build.sh
          cd ../Coreboot && make nintendo_switch_defconfig && make
      - name: NintendoSwitchPkg
        uses: actions/upload-artifact@v3
        with:
          name: NintendoSwitchPkg
          path: NintendoSwitchPkg/
